# Generated by Django 4.2.7 on 2025-12-24 07:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('carnet', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('first_name', models.CharField(max_length=100, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Formato de teléfono inválido', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono')),
                ('date_of_birth', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('address', models.TextField(verbose_name='Dirección')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('has_scholarship', models.BooleanField(default=False, verbose_name='Tiene beca')),
                ('scholarship_type', models.CharField(choices=[('COMPLETA', 'Beca Completa'), ('MEDIA', 'Media Beca'), ('NINGUNA', 'Sin Beca')], default='NINGUNA', max_length=20, verbose_name='Tipo de beca')),
                ('pensum_closed', models.BooleanField(default=False, verbose_name='Pensum cerrado')),
                ('thesis_started', models.BooleanField(default=False, verbose_name='Tesis iniciada')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('contract_generated', models.BooleanField(default=False, verbose_name='Contrato generado')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Archivo de contrato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('BACHILLERATO_ORIGINAL', 'Certificado de Bachillerato (Original)'), ('BACHILLERATO_COPIA1', 'Certificado de Bachillerato (Copia 1)'), ('BACHILLERATO_COPIA2', 'Certificado de Bachillerato (Copia 2)'), ('NACIMIENTO_ORIGINAL', 'Acta de Nacimiento (Original)'), ('NACIMIENTO_COPIA1', 'Acta de Nacimiento (Copia 1)'), ('NACIMIENTO_COPIA2', 'Acta de Nacimiento (Copia 2)'), ('CURP', 'CURP'), ('MEDICO', 'Certificado Médico'), ('FOTO_DIGITAL', 'Fotografía Digital para Carnet'), ('FOTO_FISICA1', 'Fotografía Física 1'), ('FOTO_FISICA2', 'Fotografía Física 2'), ('DOMICILIO', 'Comprobante de Domicilio')], max_length=50, verbose_name='Tipo de documento')),
                ('file', models.FileField(blank=True, null=True, upload_to='student_documents/', verbose_name='Archivo')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('RECIBIDO', 'Recibido'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Documento de Estudiante',
                'verbose_name_plural': 'Documentos de Estudiantes',
                'unique_together': {('student', 'document_type')},
            },
        ),
    ]
