# Generated by Django 4.2.7 on 2026-01-09 23:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
from datetime import datetime


def transfer_last_name_data(apps, schema_editor):
    """Transferir datos de last_name a first_last_name"""
    Student = apps.get_model('students', 'Student')
    for student in Student.objects.all():
        if hasattr(student, 'last_name') and student.last_name and not student.first_last_name:
            student.first_last_name = student.last_name
            student.save(update_fields=['first_last_name'])


def complete_enrollment_data(apps, schema_editor):
    """Completar datos en Enrollment desde Student y Career"""
    Enrollment = apps.get_model('students', 'Enrollment')
    current_year = datetime.now().year
    
    for enrollment in Enrollment.objects.all():
        updated = False
        
        # Completar career desde student si no está especificada
        if not enrollment.career and enrollment.student and enrollment.student.career:
            enrollment.career = enrollment.student.career
            updated = True
        
        # Completar school_year si no está especificado
        if not enrollment.school_year:
            enrollment.school_year = current_year
            updated = True
        
        # Completar institutional_id con carnet si no está especificado
        if not enrollment.institutional_id and enrollment.student and enrollment.student.carnet:
            enrollment.institutional_id = enrollment.student.carnet
            updated = True
        
        # Completar campos desde Career si está disponible
        if enrollment.career:
            if not enrollment.cct and enrollment.career.cct:
                enrollment.cct = enrollment.career.cct
                updated = True
            if not enrollment.rvoe_agreement_number and enrollment.career.rvoe_agreement_number:
                enrollment.rvoe_agreement_number = enrollment.career.rvoe_agreement_number
                updated = True
            if not enrollment.rvoe_agreement_date and enrollment.career.rvoe_agreement_date:
                enrollment.rvoe_agreement_date = enrollment.career.rvoe_agreement_date
                updated = True
        
        if updated:
            enrollment.save()


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_career_career_key_career_cct_career_institution_key_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntecedenteAcademico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Antecedente Académico',
                'verbose_name_plural': 'Antecedentes Académicos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntidadFederativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código de la entidad')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la entidad')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Entidad Federativa',
                'verbose_name_plural': 'Entidades Federativas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código del idioma')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del idioma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Idioma',
                'verbose_name_plural': 'Idiomas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ModalidadEducativa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Modalidad Educativa',
                'verbose_name_plural': 'Modalidades Educativas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NecesidadEducativaEspecial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('tipo', models.CharField(choices=[('DISCAPACIDAD', 'Discapacidad'), ('APTITUD_SOBRESALIENTE', 'Aptitud Sobresaliente'), ('NINGUNA', 'Ninguna')], default='NINGUNA', max_length=25, verbose_name='Tipo')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Necesidad Educativa Especial',
                'verbose_name_plural': 'Necesidades Educativas Especiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NivelEducativo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Nivel Educativo',
                'verbose_name_plural': 'Niveles Educativos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código del país')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del país')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'ordering': ['-school_year', '-enrollment_date'], 'verbose_name': 'Inscripción', 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='career',
            field=models.ForeignKey(blank=True, help_text='Si no se especifica, se toma del estudiante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_enrollments', to='academics.career', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='cct',
            field=models.CharField(blank=True, help_text='Texto, 10 caracteres, de la institución particular titular del RVOE. Si no se especifica, se toma de la carrera', max_length=10, null=True, verbose_name='Clave del Centro de Trabajo (CCT)'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(choices=[('INSCRIPCION', 'Inscripción'), ('REINSCRIPCION', 'Reinscripción')], default='INSCRIPCION', help_text='Inscripción o Reinscripción', max_length=20, verbose_name='Estatus del alumno'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='institutional_id',
            field=models.CharField(blank=True, help_text='Texto, máximo 20 caracteres. Si no se especifica, se usa el carnet del estudiante', max_length=20, null=True, verbose_name='Matrícula institucional del alumno'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rvoe_agreement_date',
            field=models.CharField(blank=True, help_text='Numérico, 8 caracteres, formato aaaammdd. Si no se especifica, se toma de la carrera', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Debe ser formato aaaammdd (8 dígitos)', regex='^\\d{8}$')], verbose_name='Fecha del Acuerdo de RVOE'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='rvoe_agreement_number',
            field=models.CharField(blank=True, help_text='Texto, máximo 70 caracteres. Si no se especifica, se toma de la carrera', max_length=70, null=True, verbose_name='Número de Acuerdo de RVOE'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_year',
            field=models.IntegerField(blank=True, help_text='Numérico, 4 caracteres, por ejemplo: 2017. Si no se especifica, se usa el año actual', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='Año del ciclo escolar'),
        ),
        migrations.AddField(
            model_name='student',
            name='first_last_name',
            field=models.CharField(blank=True, help_text='Máximo 70 caracteres, conforme al acta de nacimiento', max_length=70, null=True, verbose_name='Primer apellido del alumno'),
        ),
        migrations.AddField(
            model_name='student',
            name='second_last_name',
            field=models.CharField(blank=True, help_text='Máximo 70 caracteres; dejar en blanco si no cuenta con segundo apellido', max_length=70, null=True, verbose_name='Segundo apellido del alumno'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20, verbose_name='Estado administrativo'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AlterField(
            model_name='student',
            name='carnet',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Carnet'),
        ),
        migrations.AlterField(
            model_name='student',
            name='curp',
            field=models.CharField(help_text='18 caracteres, proporcionada por RENAPO', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de CURP inválido', regex='^[A-Z]{4}\\d{6}[HM][A-Z]{5}[0-9A-Z]\\d$')], verbose_name='CURP del alumno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(help_text='Conforme al acta de nacimiento', verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de primera inscripción'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(help_text='Máximo 70 caracteres, tal como aparece en el acta de nacimiento', max_length=70, verbose_name='Nombre(s) del alumno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], help_text='M = Mujer, H = Hombre', max_length=1, verbose_name='Género'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'school_year', 'career')},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='educational_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.niveleducativo', verbose_name='Nivel educativo'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='educational_modality',
            field=models.ForeignKey(blank=True, help_text='Escolar, no escolarizada o mixta', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.modalidadeducativa', verbose_name='Modalidad educativa'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Conforme al CCT', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='students.turno', verbose_name='Turno'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_background',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.antecedenteacademico', verbose_name='Presenta antecedente académico'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_country',
            field=models.ForeignKey(blank=True, help_text='Conforme al acta de nacimiento o documento equivalente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='born_students', to='students.pais', verbose_name='País de nacimiento'),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_state',
            field=models.ForeignKey(blank=True, help_text='Conforme al acta de nacimiento o documento equivalente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='born_students', to='students.entidadfederativa', verbose_name='Entidad federativa o ciudad de nacimiento'),
        ),
        migrations.AddField(
            model_name='student',
            name='native_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='native_speakers', to='students.idioma', verbose_name='Idioma o lengua natural del alumno'),
        ),
        migrations.AddField(
            model_name='student',
            name='origin_country',
            field=models.ForeignKey(blank=True, help_text='Únicamente si realizó estudios previos en dicho país', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_students', to='students.pais', verbose_name='País de procedencia'),
        ),
        migrations.AddField(
            model_name='student',
            name='special_educational_need',
            field=models.ForeignKey(blank=True, help_text='En caso de discapacidad o aptitudes sobresalientes', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students_with_need', to='students.necesidadeducativaespecial', verbose_name='Necesidad educativa especial'),
        ),
        # Transferir datos de last_name a first_last_name antes de eliminar el campo
        migrations.RunPython(transfer_last_name_data, migrations.RunPython.noop),
        # Completar datos en Enrollment
        migrations.RunPython(complete_enrollment_data, migrations.RunPython.noop),
        # Ahora sí eliminar last_name
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
