# Generated by Django 4.2.7 on 2026-01-09 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_antecedenteacademico_entidadfederativa_idioma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='contract_scanned',
            field=models.FileField(blank=True, null=True, upload_to='contracts/scanned/', verbose_name='Contrato escaneado'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='contract_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de subida del contrato escaneado'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_officially_enrolled',
            field=models.BooleanField(default=False, help_text='True cuando el contrato escaneado ha sido subido y aprobado', verbose_name='Oficialmente inscrito'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='contract_file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='Archivo de contrato generado'),
        ),
    ]
