# Generated by Django 4.2.7 on 2026-01-09 23:46

from django.db import migrations, models
import django.db.models.deletion


def assign_mexico_to_existing_entities(apps, schema_editor):
    """Asignar México como país por defecto a las entidades federativas existentes"""
    Pais = apps.get_model('students', 'Pais')
    EntidadFederativa = apps.get_model('students', 'EntidadFederativa')
    
    # Buscar México por código o nombre
    mexico = None
    try:
        mexico = Pais.objects.filter(codigo='MX').first()
        if not mexico:
            mexico = Pais.objects.filter(nombre__icontains='México').first()
        if not mexico:
            mexico = Pais.objects.filter(nombre__icontains='Mexico').first()
        
        # Si no existe México, crearlo
        if not mexico:
            mexico = Pais.objects.create(
                codigo='MX',
                nombre='México',
                is_active=True
            )
        
        # Asignar México a todas las entidades que no tengan país
        EntidadFederativa.objects.filter(pais__isnull=True).update(pais=mexico)
    except Exception as e:
        # Si hay un error, simplemente continuar - los datos se pueden migrar después
        pass


def reverse_assign_mexico(apps, schema_editor):
    """Reversa: no hacer nada, simplemente dejar null"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_enrollment_contract_scanned_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entidadfederativa',
            options={'ordering': ['pais', 'nombre'], 'verbose_name': 'Entidad Federativa / Estado / Ciudad', 'verbose_name_plural': 'Entidades Federativas / Estados / Ciudades'},
        ),
        migrations.AddField(
            model_name='entidadfederativa',
            name='pais',
            field=models.ForeignKey(blank=True, help_text='País al que pertenece esta entidad federativa, estado o ciudad', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entidades', to='students.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='entidadfederativa',
            name='codigo',
            field=models.CharField(max_length=10, verbose_name='Código de la entidad'),
        ),
        migrations.AlterField(
            model_name='entidadfederativa',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la entidad'),
        ),
        migrations.AlterUniqueTogether(
            name='entidadfederativa',
            unique_together={('pais', 'codigo')},
        ),
        migrations.AddIndex(
            model_name='entidadfederativa',
            index=models.Index(fields=['pais', 'is_active'], name='students_en_pais_id_879606_idx'),
        ),
        # Migración de datos: asignar México a entidades existentes
        migrations.RunPython(assign_mexico_to_existing_entities, reverse_assign_mexico),
    ]
