# Generated by Django 4.2.7 on 2026-01-10 18:03

import django.core.validators
from django.db import migrations, models
import students.models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_add_pais_to_entidad_federativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='curp',
            field=models.CharField(help_text='18 caracteres: 4 letras + 6 dígitos + H/M + 5 letras + 1 alfanumérico + 1 dígito. Ejemplo: ABCD123456HHIJKLM01', max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de CURP inválido. Debe tener: 4 letras + 6 dígitos + H/M + 5 letras + 1 alfanumérico + 1 dígito', regex='^[A-Z]{4}\\d{6}[HM][A-Z]{5}[0-9A-Z]\\d$')], verbose_name='CURP del alumno'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(help_text='Número telefónico: solo se permite el signo + y números. Ejemplo: +1234567890', max_length=20, validators=[students.models.validate_phone], verbose_name='Teléfono'),
        ),
    ]
