# Generated by Django 4.2.7 on 2026-01-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_curp_alter_student_phone'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('career__isnull', False)), fields=('student', 'school_year', 'career'), name='unique_enrollment_per_student_year_career'),
        ),
    ]
