# Generated by Django 4.2.7 on 2026-01-20 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='thesis_started',
        ),
        migrations.AddField(
            model_name='student',
            name='graduation_method_started',
            field=models.BooleanField(default=False, verbose_name='Método de graduación iniciado'),
        ),
        migrations.CreateModel(
            name='StudentDocumentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=50, verbose_name='Estado nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_document_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('student_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.studentdocument', verbose_name='Documento')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Documento',
                'verbose_name_plural': 'Historial de Estados de Documentos',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['student_document', 'changed_at'], name='students_st_student_de242d_idx'), models.Index(fields=['changed_at'], name='students_st_changed_869bbf_idx'), models.Index(fields=['student_document'], name='students_st_student_522cbc_idx')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=50, verbose_name='Estado nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='students.enrollment', verbose_name='Inscripción')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Inscripción',
                'verbose_name_plural': 'Historial de Estados de Inscripciones',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['enrollment', 'changed_at'], name='students_en_enrollm_5e2874_idx'), models.Index(fields=['changed_at'], name='students_en_changed_40c77d_idx'), models.Index(fields=['enrollment'], name='students_en_enrollm_693f59_idx')],
            },
        ),
    ]
