# Generated by Django 4.2.7 on 2026-01-20 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_change_thesis_to_graduation_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='moodle_password',
            field=models.CharField(blank=True, help_text='Contraseña generada automáticamente para acceso a la plataforma Moodle', max_length=255, null=True, verbose_name='Contraseña de Moodle'),
        ),
        migrations.AddField(
            model_name='student',
            name='moodle_username',
            field=models.CharField(blank=True, help_text='Usuario generado automáticamente para acceso a la plataforma Moodle', max_length=100, null=True, unique=True, verbose_name='Usuario de Moodle'),
        ),
    ]
