# Generated by Django 4.2.7 on 2026-01-20 22:52

from django.db import migrations, models


def remove_copy_documents(apps, schema_editor):
    """Eliminar todos los documentos de tipo copia y fotos físicas antes de cambiar el campo"""
    StudentDocument = apps.get_model('students', 'StudentDocument')
    types_to_remove = [
        'BACHILLERATO_COPIA1',
        'BACHILLERATO_COPIA2',
        'NACIMIENTO_COPIA1',
        'NACIMIENTO_COPIA2',
        'FOTO_FISICA1',
        'FOTO_FISICA2',
    ]
    StudentDocument.objects.filter(document_type__in=types_to_remove).delete()


def reverse_remove_copy_documents(apps, schema_editor):
    """No se puede revertir la eliminación de documentos"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_student_moodle_password_student_moodle_username'),
    ]

    operations = [
        migrations.RunPython(remove_copy_documents, reverse_remove_copy_documents),
        migrations.AlterField(
            model_name='studentdocument',
            name='document_type',
            field=models.CharField(choices=[('BACHILLERATO_ORIGINAL', 'Certificado de Bachillerato (Original)'), ('NACIMIENTO_ORIGINAL', 'Acta de Nacimiento (Original)'), ('CURP', 'CURP'), ('MEDICO', 'Certificado Médico'), ('FOTO_DIGITAL', 'Fotografía Digital para Carnet'), ('DOMICILIO', 'Comprobante de Domicilio')], max_length=50, verbose_name='Tipo de documento'),
        ),
    ]
