# Generated by Django 4.2.7 on 2025-12-24 07:17

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.IntegerField(unique=True, verbose_name='Código de carrera')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre de la carrera')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('total_credits', models.IntegerField(default=0, verbose_name='Total de créditos')),
                ('max_scholarships_full', models.IntegerField(default=0, verbose_name='Máximo de becas completas')),
                ('max_scholarships_half', models.IntegerField(default=0, verbose_name='Máximo de medias becas')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, verbose_name='Código del curso')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del curso')),
                ('credits', models.IntegerField(default=0, verbose_name='Créditos')),
                ('is_required', models.BooleanField(default=True, verbose_name='Obligatorio')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['cuatrimestre', 'code'],
            },
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de matrícula')),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Nota final')),
                ('status', models.CharField(choices=[('MATRICULADO', 'Matriculado'), ('EN_CURSO', 'En Curso'), ('APROBADO', 'Aprobado'), ('REPROBADO', 'Reprobado'), ('RETIRADO', 'Retirado')], default='MATRICULADO', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Matrícula de Curso',
                'verbose_name_plural': 'Matrículas de Cursos',
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Cuatrimestre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Número de cuatrimestre')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del cuatrimestre')),
            ],
            options={
                'verbose_name': 'Cuatrimestre',
                'verbose_name_plural': 'Cuatrimestres',
                'ordering': ['career', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Título de la tesis')),
                ('advisor', models.CharField(blank=True, max_length=200, verbose_name='Asesor')),
                ('status', models.CharField(choices=[('NO_INICIADA', 'No Iniciada'), ('SOLICITUD_ASESOR', 'Solicitud de Asesor'), ('REVISION_TEMA', 'Revisión de Tema'), ('APROBACION_TEMA', 'Aprobación de Tema'), ('PRIMERA_REVISION', 'Primera Revisión'), ('SEGUNDA_REVISION', 'Segunda Revisión'), ('TERCERA_REVISION', 'Tercera Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='NO_INICIADA', max_length=30, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='Fecha de defensa')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('document', models.FileField(blank=True, null=True, upload_to='thesis/', verbose_name='Documento de tesis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tesis',
                'verbose_name_plural': 'Tesis',
                'ordering': ['-created_at'],
            },
        ),
    ]
