# Generated by Django 4.2.7 on 2025-12-24 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thesis',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thesis', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='cuatrimestre',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuatrimestres', to='academics.career', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.course', verbose_name='Curso'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='students.student', verbose_name='Estudiante'),
        ),
        migrations.AddField(
            model_name='course',
            name='career',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.career', verbose_name='Carrera'),
        ),
        migrations.AddField(
            model_name='course',
            name='cuatrimestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.cuatrimestre', verbose_name='Cuatrimestre'),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.course', verbose_name='Prerequisito'),
        ),
        migrations.AlterUniqueTogether(
            name='cuatrimestre',
            unique_together={('career', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('career', 'code')},
        ),
    ]
