# Generated by Django 4.2.7 on 2026-01-09 23:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='career',
            name='career_key',
            field=models.CharField(blank=True, help_text='Texto, 10 caracteres, proporcionada por la Dirección General de Profesiones de la SEP', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Debe tener exactamente 10 caracteres', regex='^.{10}$')], verbose_name='Clave de la carrera'),
        ),
        migrations.AddField(
            model_name='career',
            name='cct',
            field=models.CharField(blank=True, help_text='Texto, 10 caracteres, de la institución particular titular del RVOE', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Debe tener exactamente 10 caracteres', regex='^.{10}$')], verbose_name='Clave del Centro de Trabajo (CCT)'),
        ),
        migrations.AddField(
            model_name='career',
            name='institution_key',
            field=models.CharField(blank=True, help_text='Texto, 10 caracteres, proporcionada por la Dirección General de Profesiones de la SEP', max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Debe tener exactamente 10 caracteres', regex='^.{10}$')], verbose_name='Clave de la institución'),
        ),
        migrations.AddField(
            model_name='career',
            name='rvoe_agreement_date',
            field=models.CharField(blank=True, help_text='Numérico, 8 caracteres, formato aaaammdd', max_length=8, null=True, validators=[django.core.validators.RegexValidator(message='Debe ser formato aaaammdd (8 dígitos)', regex='^\\d{8}$')], verbose_name='Fecha del Acuerdo de RVOE'),
        ),
        migrations.AddField(
            model_name='career',
            name='rvoe_agreement_number',
            field=models.CharField(blank=True, help_text='Texto, máximo 70 caracteres', max_length=70, null=True, verbose_name='Número de Acuerdo de RVOE'),
        ),
    ]
