# Generated by Django 4.2.7 on 2026-01-10 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_curp_alter_student_phone'),
        ('academics', '0003_career_career_key_career_cct_career_institution_key_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='CuatrimestreEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.IntegerField(help_text='Año en que se realiza la inscripción al cuatrimestre', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='Año académico')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de inscripción')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('INSCRITO', 'Inscrito'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='INSCRITO', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuatrimestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.cuatrimestre', verbose_name='Cuatrimestre')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuatrimestre_enrollments', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Inscripción a Cuatrimestre',
                'verbose_name_plural': 'Inscripciones a Cuatrimestres',
                'ordering': ['-academic_year', 'cuatrimestre__number'],
                'unique_together': {('student', 'cuatrimestre', 'academic_year')},
            },
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='cuatrimestre_enrollment',
            field=models.ForeignKey(blank=True, help_text='Inscripción al cuatrimestre específico (opcional para mantener compatibilidad)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='academics.cuatrimestreenrollment', verbose_name='Inscripción al Cuatrimestre'),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['student', 'cuatrimestre_enrollment'], name='academics_c_student_77a19a_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('cuatrimestre_enrollment__isnull', True)), fields=('student', 'course'), name='unique_student_course_without_cuatrimestre'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('cuatrimestre_enrollment__isnull', False)), fields=('student', 'course', 'cuatrimestre_enrollment'), name='unique_student_course_per_cuatrimestre'),
        ),
        migrations.AddIndex(
            model_name='cuatrimestreenrollment',
            index=models.Index(fields=['student', 'academic_year'], name='academics_c_student_008dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='cuatrimestreenrollment',
            index=models.Index(fields=['academic_year', 'cuatrimestre'], name='academics_c_academi_b5cdb2_idx'),
        ),
    ]
