# Generated by Django 4.2.7 on 2026-01-12 19:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_rename_trimester_to_cuatrimestre'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, verbose_name='Día')),
                ('start_time', models.TimeField(verbose_name='Hora de inicio')),
                ('end_time', models.TimeField(verbose_name='Hora de fin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.course', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Horario de Curso',
                'verbose_name_plural': 'Horarios de Cursos',
                'ordering': ['course', 'day', 'start_time'],
                'indexes': [models.Index(fields=['course', 'day'], name='academics_c_course__4ebb94_idx')],
            },
        ),
    ]
