# Generated by Django 4.2.7 on 2026-01-13 20:37

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_add_course_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriodConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.IntegerField(choices=[(1, 'Período 1 (Enero-Abril)'), (2, 'Período 2 (Mayo-Agosto)'), (3, 'Período 3 (Septiembre-Diciembre)')], unique=True, verbose_name='Período Académico')),
                ('penalty_percentage', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Porcentaje de mora aplicado sobre el monto del pago cuando se excede la fecha límite', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Porcentaje de Mora (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de Período Académico',
                'verbose_name_plural': 'Configuraciones de Períodos Académicos',
                'ordering': ['period'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyPaymentDueDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], unique=True, verbose_name='Mes')),
                ('due_day', models.IntegerField(default=10, help_text='Día del mes en que vence el pago (ej: 10 = día 10 de cada mes)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)], verbose_name='Día límite de pago')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fecha Límite de Pago Mensual',
                'verbose_name_plural': 'Fechas Límite de Pago Mensuales',
                'ordering': ['month'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Costo de la colegiatura para este curso', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo del curso'),
        ),
        migrations.AlterField(
            model_name='cuatrimestreenrollment',
            name='status',
            field=models.CharField(choices=[('PENDIENTE_PAGO', 'Pendiente de Pago'), ('PENDIENTE_CONFIRMACION', 'Pendiente de Confirmación'), ('EN_CURSO', 'En Curso'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE_PAGO', max_length=25, verbose_name='Estado'),
        ),
    ]
