# Generated by Django 4.2.7 on 2026-01-17 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0007_add_course_cost_and_period_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuatrimestreEnrollmentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=50, verbose_name='Estado nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Inscripción a Cuatrimestre',
                'verbose_name_plural': 'Historial de Estados de Inscripciones a Cuatrimestres',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ThesisStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=50, verbose_name='Estado nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Tesis',
                'verbose_name_plural': 'Historial de Estados de Tesis',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cuatrimestreenrollment',
            index=models.Index(condition=models.Q(('status', 'EN_CURSO')), fields=['student', 'status'], name='idx_student_en_curso'),
        ),
        migrations.AddField(
            model_name='thesisstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por'),
        ),
        migrations.AddField(
            model_name='thesisstatushistory',
            name='thesis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='academics.thesis', verbose_name='Tesis'),
        ),
        migrations.AddField(
            model_name='cuatrimestreenrollmentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuatrimestre_enrollment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por'),
        ),
        migrations.AddField(
            model_name='cuatrimestreenrollmentstatushistory',
            name='cuatrimestre_enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='academics.cuatrimestreenrollment', verbose_name='Inscripción al Cuatrimestre'),
        ),
        migrations.AddIndex(
            model_name='thesisstatushistory',
            index=models.Index(fields=['thesis', 'changed_at'], name='academics_t_thesis__64461b_idx'),
        ),
        migrations.AddIndex(
            model_name='thesisstatushistory',
            index=models.Index(fields=['changed_at'], name='academics_t_changed_c0c6cd_idx'),
        ),
        migrations.AddIndex(
            model_name='thesisstatushistory',
            index=models.Index(fields=['thesis'], name='academics_t_thesis__bf3356_idx'),
        ),
        migrations.AddIndex(
            model_name='cuatrimestreenrollmentstatushistory',
            index=models.Index(fields=['cuatrimestre_enrollment', 'changed_at'], name='academics_c_cuatrim_b6b2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='cuatrimestreenrollmentstatushistory',
            index=models.Index(fields=['changed_at'], name='academics_c_changed_8646ca_idx'),
        ),
        migrations.AddIndex(
            model_name='cuatrimestreenrollmentstatushistory',
            index=models.Index(fields=['cuatrimestre_enrollment'], name='academics_c_cuatrim_148e83_idx'),
        ),
    ]
