# Generated by Django 4.2.7 on 2026-01-18 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_add_rvoe_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuatrimestreenrollment',
            name='pre_assign_course_ids',
            field=models.JSONField(blank=True, default=list, help_text='Lista temporal de IDs de cursos pre-asignados (se limpia al confirmar)', verbose_name='IDs de cursos pre-asignados'),
        ),
    ]
