# Generated by Django 4.2.7 on 2026-01-20 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0007_change_thesis_to_graduation_method'),
        ('academics', '0011_cuatrimestreenrollment_pre_assign_course_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationMethod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_type', models.CharField(choices=[('EXAMEN_PROFESIONAL', 'Examen Profesional'), ('TESINA', 'Tesina'), ('TESIS', 'Tesis'), ('DIPLOMADO', 'Diplomado')], max_length=30, verbose_name='Método de Graduación')),
                ('title', models.CharField(blank=True, max_length=500, verbose_name='Título')),
                ('advisor', models.CharField(blank=True, max_length=200, verbose_name='Asesor')),
                ('status', models.CharField(choices=[('NO_INICIADA', 'No Iniciada'), ('SOLICITUD_ASESOR', 'Solicitud de Asesor'), ('REVISION_TEMA', 'Revisión de Tema'), ('APROBACION_TEMA', 'Aprobación de Tema'), ('PRIMERA_REVISION', 'Primera Revisión'), ('SEGUNDA_REVISION', 'Segunda Revisión'), ('TERCERA_REVISION', 'Tercera Revisión'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='NO_INICIADA', max_length=30, verbose_name='Estado')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Fecha de inicio')),
                ('defense_date', models.DateField(blank=True, null=True, verbose_name='Fecha de defensa/examen')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('document', models.FileField(blank=True, null=True, upload_to='graduation_methods/', verbose_name='Documento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_method', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Método de Graduación',
                'verbose_name_plural': 'Métodos de Graduación',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GraduationMethodStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=50, verbose_name='Estado nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thesis_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('graduation_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='academics.graduationmethod', verbose_name='Método de Graduación')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Método de Graduación',
                'verbose_name_plural': 'Historial de Estados de Métodos de Graduación',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RemoveField(
            model_name='thesisstatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='thesisstatushistory',
            name='thesis',
        ),
        migrations.DeleteModel(
            name='Thesis',
        ),
        migrations.DeleteModel(
            name='ThesisStatusHistory',
        ),
        migrations.AddIndex(
            model_name='graduationmethodstatushistory',
            index=models.Index(fields=['graduation_method', 'changed_at'], name='academics_g_graduat_763a1e_idx'),
        ),
        migrations.AddIndex(
            model_name='graduationmethodstatushistory',
            index=models.Index(fields=['changed_at'], name='academics_g_changed_c124f1_idx'),
        ),
        migrations.AddIndex(
            model_name='graduationmethodstatushistory',
            index=models.Index(fields=['graduation_method'], name='academics_g_graduat_8ad4a5_idx'),
        ),
    ]
