# Generated by Django 4.2.7 on 2026-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_change_thesis_to_graduation_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicperiodconfig',
            name='period',
            field=models.IntegerField(choices=[(1, 'Período 1 (Febrero-Mayo)'), (2, 'Período 2 (Junio-Agosto)'), (3, 'Período 3 (Septiembre-Diciembre)')], unique=True, verbose_name='Período Académico'),
        ),
    ]
