# Generated by Django 4.2.7 on 2025-12-24 07:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scholarship_type', models.CharField(choices=[('COMPLETA', 'Beca Completa'), ('MEDIA', 'Media Beca')], max_length=20, verbose_name='Tipo de beca')),
                ('start_date', models.DateField(verbose_name='Fecha de inicio')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Fecha de fin')),
                ('status', models.CharField(choices=[('ACTIVA', 'Activa'), ('SUSPENDIDA', 'Suspendida'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=20, verbose_name='Estado')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje de descuento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scholarship', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Beca',
                'verbose_name_plural': 'Becas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('monthly_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto mensual')),
                ('enrollment_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cuota de inscripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_configs', to='academics.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Configuración de Pago',
                'verbose_name_plural': 'Configuraciones de Pago',
                'unique_together': {('career',)},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('TRANSFERENCIA', 'Transferencia'), ('TARJETA', 'Tarjeta'), ('EFECTIVO', 'Efectivo')], max_length=20, verbose_name='Método de pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('month', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], verbose_name='Mes')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('payment_date', models.DateField(auto_now_add=True, verbose_name='Fecha de pago')),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('transfer_receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Comprobante de transferencia')),
                ('receipt_number', models.CharField(blank=True, max_length=50, verbose_name='Número de recibo')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='Últimos 4 dígitos de tarjeta')),
                ('transaction_id', models.CharField(blank=True, max_length=100, verbose_name='ID de transacción')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-payment_date'],
                'unique_together': {('student', 'month', 'year')},
            },
        ),
    ]
