# Generated by Django 4.2.7 on 2026-01-05 03:51

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto fijo (opcional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('requires_career', models.BooleanField(default=False, verbose_name='Requiere carrera')),
                ('requires_semester', models.BooleanField(default=False, verbose_name='Requiere semestre/trimestre')),
                ('requires_month', models.BooleanField(default=False, verbose_name='Requiere mes')),
                ('requires_year', models.BooleanField(default=False, verbose_name='Requiere año')),
                ('requires_quantity', models.BooleanField(default=False, verbose_name='Requiere cantidad')),
                ('has_penalty', models.BooleanField(default=False, verbose_name='Aplica mora')),
                ('penalty_due_date_field', models.CharField(blank=True, help_text='Campo que determina la fecha límite (ej: "month", "semester", "year")', max_length=50, verbose_name='Campo de fecha límite')),
                ('penalty_days_offset', models.IntegerField(default=0, help_text='Días después de la fecha límite para aplicar mora (0 = mismo día)', verbose_name='Días de gracia')),
                ('penalty_type', models.CharField(blank=True, choices=[('FIXED', 'Monto Fijo'), ('PERCENTAGE', 'Porcentaje'), ('DAILY_FIXED', 'Monto Fijo Diario'), ('DAILY_PERCENTAGE', 'Porcentaje Diario')], max_length=20, verbose_name='Tipo de mora')),
                ('penalty_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto fijo de mora (si tipo es FIXED o DAILY_FIXED)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto de mora')),
                ('penalty_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de mora sobre el monto base (si tipo es PERCENTAGE o DAILY_PERCENTAGE)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Porcentaje de mora (%)')),
                ('penalty_max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monto máximo de mora (opcional, 0 = sin límite)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto máximo de mora')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pago',
                'verbose_name_plural': 'Tipos de Pago',
                'ordering': ['code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payment',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto base (sin mora)'),
        ),
        migrations.AddField(
            model_name='payment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago'),
        ),
        migrations.AddField(
            model_name='payment',
            name='penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto de mora aplicado'),
        ),
        migrations.AddField(
            model_name='payment',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='payment',
            name='semester',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semestre/Trimestre'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')], null=True, verbose_name='Mes'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='payments.paymenttype', verbose_name='Tipo de pago'),
        ),
    ]
