# Generated by Django 4.2.7 on 2026-01-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paymenttype_alter_payment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transfer_receipt',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Comprobante de pago'),
        ),
    ]
