# Generated by Django 4.2.7 on 2026-01-13 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_add_course_cost_and_period_config'),
        ('payments', '0003_add_payment_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cuatrimestre_enrollment',
            field=models.ForeignKey(blank=True, help_text='Inscripción al cuatrimestre relacionada con este pago (inscripción o colegiatura)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='academics.cuatrimestreenrollment', verbose_name='Inscripción al Cuatrimestre'),
        ),
    ]
