# Generated by Django 4.2.7 on 2026-01-17 19:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0006_add_payment_amount_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, help_text='ID del Payment Intent de Stripe para rastrear el pago', max_length=255, null=True, unique=True, verbose_name='Stripe Payment Intent ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='DEPRECATED: Usar final_amount. Se mantiene para compatibilidad.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(help_text='ID único del evento de Stripe', max_length=255, unique=True, verbose_name='Stripe Event ID')),
                ('event_type', models.CharField(help_text='Tipo de evento de Stripe (ej: payment_intent.succeeded)', max_length=100, verbose_name='Tipo de evento')),
                ('payment_intent_id', models.CharField(blank=True, help_text='ID del Payment Intent relacionado', max_length=255, null=True, verbose_name='Payment Intent ID')),
                ('processed', models.BooleanField(default=False, help_text='Indica si el evento ya fue procesado', verbose_name='Procesado')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de procesamiento')),
                ('error_message', models.TextField(blank=True, help_text='Mensaje de error si el procesamiento falló', verbose_name='Mensaje de error')),
                ('raw_data', models.JSONField(blank=True, help_text='Datos completos del evento para debugging', null=True, verbose_name='Datos del evento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evento de Webhook de Stripe',
                'verbose_name_plural': 'Eventos de Webhook de Stripe',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='payments_st_stripe__a444ea_idx'), models.Index(fields=['payment_intent_id'], name='payments_st_payment_bf60b5_idx'), models.Index(fields=['processed'], name='payments_st_process_0ea60a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=50, verbose_name='Estado nuevo')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cambio')),
                ('comment', models.TextField(blank=True, verbose_name='Comentario')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='payments.payment', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Historial de Estado de Pago',
                'verbose_name_plural': 'Historial de Estados de Pagos',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['payment', 'changed_at'], name='payments_pa_payment_cd090a_idx'), models.Index(fields=['changed_at'], name='payments_pa_changed_c50ca1_idx'), models.Index(fields=['payment'], name='payments_pa_payment_b8d7e7_idx')],
            },
        ),
    ]
