# Generated by Django 4.2.7 on 2026-01-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_payment_stripe_payment_intent_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Fecha programada para el pago (día 1 del mes correspondiente para colegiaturas mensuales)', null=True, verbose_name='Fecha programada de pago'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('NO_PAGADO', 'No Pagado'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('MORA', 'Mora')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
    ]
