# Generated by Django 4.2.7 on 2026-01-22 22:19

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_payment_date_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='DEPRECATED: Usar final_amount. Se mantiene para compatibilidad.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto final a pagar: original_amount - scholarship_discount_amount + penalty_amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto final'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto sin beca ni mora (monto base del pago)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto original'),
        ),
        migrations.AlterField(
            model_name='paymenttype',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Monto fijo (opcional)'),
        ),
    ]
