# Generated by Django 4.2.7 on 2025-12-24 07:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre de la plantilla')),
                ('document_type', models.CharField(choices=[('CONTRACT', 'Contrato'), ('CERTIFICATE', 'Certificado'), ('TRANSCRIPT', 'Acta de Calificaciones')], max_length=50, verbose_name='Tipo de documento')),
                ('template_file', models.FileField(upload_to='document_templates/', verbose_name='Archivo de plantilla')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Documento',
                'verbose_name_plural': 'Plantillas de Documentos',
            },
        ),
    ]
