# Generated by Django 4.2.7 on 2026-01-20 23:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, help_text='Nombre de usuario al momento de la acción', max_length=150, null=True, verbose_name='Nombre de usuario')),
                ('action', models.CharField(choices=[('CREATE', 'Crear'), ('UPDATE', 'Actualizar'), ('DELETE', 'Eliminar'), ('APPROVE', 'Aprobar'), ('REJECT', 'Rechazar'), ('VIEW', 'Consultar'), ('EXPORT', 'Exportar')], help_text='Tipo de acción realizada', max_length=20, verbose_name='Acción')),
                ('object_id', models.CharField(help_text='ID del registro afectado', max_length=255, verbose_name='ID del objeto')),
                ('model_name', models.CharField(help_text='Nombre del modelo afectado (app_label.ModelName)', max_length=255, verbose_name='Nombre del modelo')),
                ('data_snapshot', models.JSONField(blank=True, default=dict, help_text='Datos del registro al momento de la acción (JSON)', verbose_name='Snapshot de datos')),
                ('previous_data', models.JSONField(blank=True, default=dict, help_text='Datos anteriores del registro (para acciones UPDATE)', verbose_name='Datos anteriores')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Campos modificados y sus valores anteriores/nuevos', verbose_name='Cambios')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó la acción', null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navegador o cliente utilizado', null=True, verbose_name='User Agent')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Información adicional de contexto (comentarios, razones, etc.)', verbose_name='Metadatos')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de la acción', verbose_name='Fecha y hora')),
                ('content_type', models.ForeignKey(help_text='Modelo afectado', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de contenido')),
                ('user', models.ForeignKey(blank=True, help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_audit_timesta_901180_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx'), models.Index(fields=['model_name', '-timestamp'], name='audit_audit_model_n_ad1f4e_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx')],
            },
        ),
    ]
