# Generated by Django 4.2.7 on 2026-01-09 23:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_enrollment_contract_scanned_and_more'),
        ('academics', '0003_career_career_key_career_cct_career_institution_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_year', models.IntegerField(help_text='Numérico, 4 caracteres, correspondiente al año en que el alumno fue certificado o titulado', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)], verbose_name='Año del ciclo escolar')),
                ('curp', models.CharField(help_text='18 caracteres, clave única de registro de población', max_length=18, validators=[django.core.validators.RegexValidator(message='Formato de CURP inválido', regex='^[A-Z]{4}\\d{6}[HM][A-Z]{5}[0-9A-Z]\\d$')], verbose_name='CURP del alumno')),
                ('general_average', models.DecimalField(blank=True, decimal_places=2, help_text='Obligatorio únicamente cuando se trate de un Certificado', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Promedio general')),
                ('issuance_date', models.CharField(help_text='Numérico, 8 caracteres, formato aaaammdd', max_length=8, validators=[django.core.validators.RegexValidator(message='Debe ser formato aaaammdd (8 dígitos)', regex='^\\d{8}$')], verbose_name='Fecha de expedición del documento')),
                ('document_folio', models.CharField(help_text='Máximo 20 caracteres; corresponde al folio asignado por la institución educativa', max_length=20, verbose_name='Folio del documento')),
                ('is_sep_registered', models.BooleanField(default=False, help_text='Indica si el documento ha sido registrado en la SEP', verbose_name='Registrado en SEP')),
                ('sep_registration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de registro SEP')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/academic/', verbose_name='Archivo del certificado generado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certificado Académico',
                'verbose_name_plural': 'Certificados Académicos',
                'ordering': ['-school_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(choices=[('CERTIFICADO_TOTAL', 'Certificado Total'), ('CERTIFICADO_PARCIAL', 'Certificado Parcial'), ('TITULO', 'Título'), ('DIPLOMA', 'Diploma'), ('GRADO', 'Grado')], max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Estatus de Registro',
                'verbose_name_plural': 'Estatus de Registro',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UniversityTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_name', models.CharField(help_text='Nombre completo del título universitario', max_length=200, verbose_name='Nombre del título')),
                ('pensum_completed', models.BooleanField(default=False, help_text='Indica si el estudiante completó el pensum', verbose_name='Pensum completado')),
                ('all_courses_approved', models.BooleanField(default=False, help_text='Indica si todos los cursos requeridos fueron aprobados', verbose_name='Todos los cursos aprobados')),
                ('thesis_approved', models.BooleanField(blank=True, default=False, help_text='Indica si la tesis fue aprobada (si aplica)', null=True, verbose_name='Tesis aprobada')),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Promedio general')),
                ('issuance_date', models.DateField(blank=True, null=True, verbose_name='Fecha de expedición')),
                ('requirements_met', models.BooleanField(default=False, help_text='Indica si todos los requisitos para emitir el título fueron cumplidos', verbose_name='Requisitos cumplidos')),
                ('is_printed', models.BooleanField(default=False, help_text='Indica si el título ha sido impreso', verbose_name='Impreso')),
                ('title_file', models.FileField(blank=True, null=True, upload_to='certificates/titles/', verbose_name='Archivo del título generado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_certificate', models.OneToOneField(blank=True, help_text='Certificado académico SEP asociado al título', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='university_title', to='certificates.academiccertificate', verbose_name='Certificado académico asociado')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='university_title', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Título Universitario',
                'verbose_name_plural': 'Títulos Universitarios',
                'ordering': ['-issuance_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_name', models.CharField(help_text='Nombre descriptivo del certificado de cursos', max_length=200, verbose_name='Nombre del certificado')),
                ('total_courses', models.IntegerField(default=0, help_text='Número total de cursos incluidos', verbose_name='Total de cursos')),
                ('average_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Promedio de calificaciones')),
                ('issuance_date', models.DateField(auto_now_add=True, verbose_name='Fecha de expedición')),
                ('is_printed', models.BooleanField(default=False, help_text='Indica si el certificado ha sido impreso', verbose_name='Impreso')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/courses/', verbose_name='Archivo del certificado generado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_enrollments', models.ManyToManyField(help_text='Cursos aprobados incluidos en el certificado', related_name='course_certificates', to='academics.courseenrollment', verbose_name='Matrículas de cursos')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_certificates', to='students.student', verbose_name='Estudiante')),
            ],
            options={
                'verbose_name': 'Certificado de Cursos',
                'verbose_name_plural': 'Certificados de Cursos',
                'ordering': ['-issuance_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='academiccertificate',
            name='document_type',
            field=models.ForeignKey(help_text='Certificado Total, Certificado Parcial, Título, Diploma o Grado', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.documenttype', verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='academiccertificate',
            name='registration_status',
            field=models.ForeignKey(help_text='Certificado o Título', on_delete=django.db.models.deletion.PROTECT, related_name='certificates', to='certificates.registrationstatus', verbose_name='Estatus del registro'),
        ),
        migrations.AddField(
            model_name='academiccertificate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_certificates', to='students.student', verbose_name='Estudiante'),
        ),
    ]
