# Generated by Django 4.2.7 on 2026-01-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universitytitle',
            name='thesis_approved',
            field=models.BooleanField(blank=True, default=False, help_text='Indica si el método de graduación fue aprobado (si aplica)', null=True, verbose_name='Método de graduación aprobado'),
        ),
    ]
